### ISSUE TITLE
我可以用自己的數據集嗎

### ISSUE THREAD

**Issue by henrychou1233** [JustinTebbe/Dynamic-noise-AD#2]
我想用這篇論文做我的數據集
但我現在只有正樣本
幾個異常照片還有ground truth
把它包成跟mvtec dataset 一樣
這樣子是可行的嗎
"C:\Users\user\OneDrive\桌面\Dynamic-noise-AD-master\MVTec\capsule\train\good"
"C:\Users\user\OneDrive\桌面\Dynamic-noise-AD-master\MVTec\capsule\test\good"
"C:\Users\user\OneDrive\桌面\Dynamic-noise-AD-master\MVTec\capsule\test\poke"
"C:\Users\user\OneDrive\桌面\Dynamic-noise-AD-master\MVTec\capsule\ground_truth"

mvtec跟capsule我是故意命名跟mvtec一樣的

**Comment by JustinTebbe** [comment]
Hi Henry,
if I understand correctly, then you want to use your own dataset and you structured it like the mvtec dataset? That should  absolutely be feasible and work. Just make sure that the config.yaml is also pointing to the correct data_dir and data name should be MVTec. Please also keep in mind that the ground_truth folder has subfolders for the defect categories e.g for your "poke" example:
C:\Users\user\OneDrive\桌面\Dynamic-noise-AD-master\MVTec\capsule\ground_truth**\poke**
